services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama pull llama3.2:3b && ollama serve"

  observance-app:
    build: .
    container_name: observance-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app   
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data:
